import Script from "next/script"


export const metadata = {
  title: 'Editor GrapesJS',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-BR">
      <Script  src="https://cdn.ckeditor.com/4.21.0/standard/ckeditor.js"/>
      <body>{children}</body>
    </html>
  )
}
